[project]
name = "confidentllm"
version = "0.6.0"
description = "Evaluate the confidence of various LLM models using different confidence methods and generation techniques."
authors = [{ name = "Carel van Niekerk", email = "cvanniekerk@hhu.de" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate >= 0.34",
    "colorlog >= 6.8",
    "datasets >= 2.20",
    "hydra-zen >= 0.13",
    "matplotlib >= 3.9.1",
    "numpy >= 1.26",
    "openai>=1.65.2",
    "pandas >= 2.2.2",
    "pandas-stubs >= 2.2.2.240807",
    "peft >= 0.15",
    "pydantic >= 2.8.2",
    "python-dotenv>=1.0.1",
    "torch >= 2.4.0",
    "transformers >= 4.51",
    "trl >= 0.12.0",
    "tqdm >= 4.66.0",
    "types-tqdm >= 4.66.0.20240417",
    "vertexai>=1.71.1",
    "wandb >= 0.18",
]

[dependency-groups]
dev = ["pytest >= 8", "pytest-cov >= 6"]

[tool.uv]
default-groups = []

# Script entry points for various tasks (e.g. question answering)
[project.scripts]
download-and-sync = "confidentllm.scripts:download_and_sync"
question-answering = "confidentllm.scripts:question_answering"
reinforcement-learning = "confidentllm.scripts:reinforcement_learning"
reporting = "confidentllm.scripts:reporting"
reward-model-evaluation = "confidentllm.scripts:reward_model_evaluation"
train = "confidentllm.scripts:train"
tests = "pytest:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Configuration for Pytest
[tool.pytest.ini_options]
addopts = "--cov confidentllm --verbose --cov-report=term-missing"
filterwarnings = "error::RuntimeWarning"

# Configuration for Ruff (Python linter and formatter)
[tool.ruff]
extend = "~/.config/ruff/config.toml"
target-version = "py313"

# Configuration for Mypy (Python static type checker)
[tool.mypy]
python_version = "3.13"

[[tool.mypy.overrides]]
module = [
    "datasets",
    "datasets.*",
    "hydra_zen",
    "peft",
    "peft.*",
    "pyarrow.*",
    "torch",
    "transformers",
    "transformers.*",
    "trl",
    "vertexai",
    "vertexai.*",
]
ignore_missing_imports = true
