[tool.poetry]
name = "confidentllm"
version = "0.1.0"
description = "Evaluate the confidence of various LLM models using different confidence methods and generation techniques."
authors = ["Carel van Niekerk <cvanniekerk@hhu.de>"]
license = "Apache2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
accelerate = ">=0.34"
colorlog = "^6.8"
datasets = "^2.20"
hydra-zen = "^0.13"
matplotlib = "^3.9.1"
pandas = "^2.2.2"
pandas-stubs = "^2.2.2.240807"
peft = "^0.13.2"
pydantic = "^2.8.2"
sentencepiece = "^0.2.0"
# Torch versioning:
# Specific version for macOS with x86_64 architecture and latest version for other platforms
torch = [
    { version = "==2.2.2", markers = "platform_machine == 'x86_64' and platform_system == 'Darwin'" },
    { version = "<2.4", markers = "platform_machine != 'x86_64' or platform_system != 'Darwin'" },
]
# Numpy versioning:
# Specific version for macOS with x86_64 architecture and latest version for other platforms
numpy = [
    { version = "<2", markers = "platform_machine == 'x86_64' and platform_system == 'Darwin'" },
    { version = "*", markers = "platform_machine != 'x86_64' or platform_system != 'Darwin'" },
]
transformers = "^4.43"
trl = "^0.12.0"
tqdm = "^4.66.0"
types-tqdm = "^4.66.0.20240417"
wandb = "^0.17"

[tool.poetry.group.dev.dependencies]
pytest = "^8"
pytest-cov = "^5.0"

# Use HHU PyPI repository (Needed for HPC)
[[tool.poetry.source]]
name = "hhu"
url = "http://pypi.repo.test.hhu.de/simple/"

# Script entry points for various tasks (e.g. question answering)
[tool.poetry.scripts]
download-and-sync = "confidentllm.scripts:download_and_sync"
mathematical-reasoning = "confidentllm.scripts:mathematical_reasoning"
reporting = "confidentllm.scripts:reporting"
reward-model-training = "confidentllm.scripts:reward_model_training"
tests = "pytest:main"

# Configuration for Pytest
[tool.pytest.ini_options]
addopts = "--cov confidentllm --verbose --cov-report=term-missing"
filterwarnings = "error::RuntimeWarning"

# Configuration for Ruff (Python linter and formatter)
[tool.ruff]
extend = "~/.config/ruff/config.toml"
target-version = "py312"

# Configuration for Mypy (Python static type checker)
[tool.mypy]
python_version = "3.12"

[[tool.mypy.overrides]]
module = [
    "datasets",
    "hydra-zen",
    "peft",
    "peft.mapping",
    "peft.peft_models",
    "peft.utils.peft_types",
    "torch",
    "transformers",
    "transformers.generation",
    "transformers.tokenization_utils_base",
    "trl",
]
ignore_missing_imports = true
